In [2]:
import numpy as np

arr = [3,5,7,9]
print(type(arr))

<class 'list'>


In [8]:
a = np.array(arr)
print(type(a))
print(a.shape)
print(a.dtype)
print(a.ndim)

<class 'numpy.ndarray'>
(4,)
int32
1


In [9]:
# get the dimesnsion of a with ndim
print(a.ndim)

1


In [12]:
b = np.array([[1,2,3], [4,5,6]])
print(b)

print(b.ndim)

b.shape

[[1 2 3]
 [4 5 6]]
2


(2, 3)

In [21]:
import numpy as pd
arr = [5,6,7,8,9]
print(type(arr))

a = np.array(arr)
print(type(a))

print(a.shape)
print(a.dtype)

# get the dimension of a with ndim
print(a.ndim)

b = np.array([[2,4,6,8], [3,6,9,12]])

print(b)

print(b.ndim)
print(b.shape)


<class 'list'>
<class 'numpy.ndarray'>
(5,)
int32
1
[[ 2  4  6  8]
 [ 3  6  9 12]]
2
(2, 4)


In [25]:
# a 2x3 with random values 
np.random.random((2, 3))

# a 2x3 arrays of zeros
np.zeros((2, 3))

# a 2x3 arrays of one
np.ones((2, 3))

# a 3x3 identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
import numpy as np

c = np.array([[9.0,8.0,7.0], [1.0,2.0,3.0]])
d = np.array([[4.0,5.0,6.0], [9.0,8.0,7.0]])

c+d

array([[13., 13., 13.],
       [10., 10., 10.]])

In [9]:
c = np.array([[9.0,8.0,7.0], [1.0,2.0,3.0]])
d = np.array([[4.0,5.0,6.0], [9.0,8.0,7.0]])
c*d

array([[36., 40., 42.],
       [ 9., 16., 21.]])

In [10]:
c = np.array([[9.0,8.0,7.0], [1.0,2.0,3.0]])
d = np.array([[4.0,5.0,6.0], [9.0,8.0,7.0]])
5/d

array([[1.25      , 1.        , 0.83333333],
       [0.55555556, 0.625     , 0.71428571]])

In [18]:
c = np.array([[9.0,8.0,7.0], [1.0,2.0,3.0]])
d = np.array([[4.0,5.0,6.0], [9.0,8.0,7.0]])

c**2


array([[81., 64., 49.],
       [ 1.,  4.,  9.]])

In [15]:
d[1, 0:2]

array([9., 8.])

In [24]:
e = np.array([[10,11,12], [13,14,15], [16,17,18], [19,20,21]])
#slicing 
e[:3, :2]

array([[10, 11],
       [13, 14],
       [16, 17]])

In [21]:
#integers
e[[2,0,3,1,], [2,1,0,2]]

array([18, 11, 19, 15])

In [25]:
#boolean meeting specific condition 
e[e>15]

array([16, 17, 18, 19, 20, 21])